#!/usr/bin/env python3
"""Generate a clearly-labelled SYNTHETIC dataset for offline demos and CI.

This exists so the engine can be exercised end to end with no network access
and no API keys. The data is generated from seeded random walks and invented
financial statements.

It is NOT market data. Every generated file carries a header comment saying so,
every symbol is prefixed ``SYN``, and the loader marks the source as
``synthetic``. Nothing in this script may be used to produce research output
that is presented as being about a real company.

    python scripts/generate_sample_data.py --out data/local
    RE__PROVIDERS__CSV_LOCAL__ROOT=local python -m research_engine.cli universe --refresh
"""

from __future__ import annotations

import argparse
import csv
import datetime as dt
import math
import random
from pathlib import Path

BANNER = ("# SYNTHETIC DATA - generated by scripts/generate_sample_data.py. "
          "Not market data. Do not use for research about real assets.")

SYMBOLS = [
    # symbol, name, sector, profile
    ("SYNCMP", "Synthetic Compounder Corp", "Technology", "compounder"),
    ("SYNGRW", "Synthetic Growth Inc", "Technology", "growth"),
    ("SYNVAL", "Synthetic Value Industries", "Industrials", "value"),
    ("SYNDCL", "Synthetic Decline Ltd", "Consumer Discretionary", "decline"),
    ("SYNIDX", "Synthetic Market Index", "Index", "index"),
]
CRYPTO = [("SYNTOK", "Synthetic Token", "synthetic-chain")]

PROFILES = {
    "compounder": dict(drift=0.00045, vol=0.014, growth=0.15, margin=0.30),
    "growth":     dict(drift=0.00070, vol=0.028, growth=0.35, margin=0.08),
    "value":      dict(drift=0.00015, vol=0.016, growth=0.03, margin=0.12),
    "decline":    dict(drift=-0.00040, vol=0.024, growth=-0.06, margin=0.02),
    "index":      dict(drift=0.00030, vol=0.010, growth=0.05, margin=0.15),
}


def write_csv(path: Path, header: list[str], rows: list[list]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as fh:
        fh.write(BANNER + "\n")
        writer = csv.writer(fh)
        writer.writerow(header)
        writer.writerows(rows)


def prices(symbol: str, profile: dict, *, years: int, seed: int,
           weekends: bool) -> list[list]:
    rng = random.Random(seed)
    rows: list[list] = []
    price = 50.0 + seed * 7
    day = dt.date.today() - dt.timedelta(days=int(years * 365.25))
    end = dt.date.today()
    while day <= end:
        if weekends or day.weekday() < 5:
            price = max(0.5, price * math.exp(rng.gauss(profile["drift"],
                                                        profile["vol"])))
            high = price * (1 + abs(rng.gauss(0, profile["vol"] / 2)))
            low = price * (1 - abs(rng.gauss(0, profile["vol"] / 2)))
            volume = int(1_000_000 * rng.uniform(0.5, 2.0))
            rows.append([day.isoformat(), round(price * (1 + rng.gauss(0, 0.003)), 4),
                         round(high, 4), round(low, 4), round(price, 4), volume,
                         round(price, 4)])
        day += dt.timedelta(days=1)
    return rows


def fundamentals(profile: dict, *, years: int, seed: int) -> list[list]:
    rng = random.Random(seed + 1000)
    rows: list[list] = []
    revenue = 1_000_000_000.0
    shares = 100_000_000.0
    this_year = dt.date.today().year
    for offset in range(years, 0, -1):
        year = this_year - offset
        revenue *= (1 + profile["growth"] + rng.gauss(0, 0.03))
        margin = max(-0.2, profile["margin"] + rng.gauss(0, 0.02))
        operating = revenue * margin
        net = operating * 0.78
        ocf = operating * 1.05
        capex = revenue * 0.06
        shares *= (1 - 0.01) if profile["growth"] > 0.05 else (1 + 0.02)
        period_end = dt.date(year, 12, 31)
        filed = dt.date(year + 1, 2, 20)
        values = {
            "revenue": revenue, "gross_profit": revenue * 0.62,
            "operating_income": operating, "net_income": net,
            "total_assets": revenue * 1.6, "total_liabilities": revenue * 0.6,
            "total_equity": revenue * 1.0, "current_assets": revenue * 0.7,
            "current_liabilities": revenue * 0.3,
            "cash_and_equivalents": revenue * 0.35,
            "long_term_debt": revenue * 0.25, "operating_cash_flow": ocf,
            "capex": capex, "shares_diluted": shares,
            "interest_expense": revenue * 0.01, "income_tax": max(0.0, net * 0.21),
            "pretax_income": net / 0.78,
            "depreciation_amortization": revenue * 0.05,
        }
        for metric, value in values.items():
            rows.append([metric, "annual", period_end.isoformat(),
                         round(value, 2), "USD", filed.isoformat(), "10-K"])
    return rows


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default="data/local")
    parser.add_argument("--years", type=int, default=8)
    args = parser.parse_args()
    root = Path(args.out)

    universe_rows = []
    for seed, (symbol, name, sector, profile_name) in enumerate(SYMBOLS, start=1):
        profile = PROFILES[profile_name]
        write_csv(root / "prices" / f"{symbol}.csv",
                  ["date", "open", "high", "low", "close", "volume", "adj_close"],
                  prices(symbol, profile, years=args.years, seed=seed, weekends=False))
        if profile_name != "index":
            write_csv(root / "fundamentals" / f"{symbol}.csv",
                      ["metric", "period", "period_end", "value", "unit",
                       "filed_date", "form"],
                      fundamentals(profile, years=args.years, seed=seed))
        universe_rows.append([symbol, name, "SYNTHETIC", sector, "Synthetic", "US"])
    write_csv(root / "universe" / "equity.csv",
              ["symbol", "name", "exchange", "sector", "industry", "country"],
              universe_rows)

    crypto_rows = []
    for seed, (symbol, name, chain) in enumerate(CRYPTO, start=90):
        write_csv(root / "prices" / f"{symbol}.csv",
                  ["date", "open", "high", "low", "close", "volume", "adj_close"],
                  prices(symbol, dict(drift=0.0005, vol=0.05), years=args.years,
                         seed=seed, weekends=True))
        crypto_rows.append([symbol, name, symbol.lower(), chain])
    write_csv(root / "universe" / "crypto.csv",
              ["symbol", "name", "coingecko_id", "chain"], crypto_rows)

    print(f"synthetic dataset written to {root.resolve()}")
    print("Reminder: this is generated data for testing the pipeline only.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
