import { useCallback, useEffect, useState } from "react";
import { api } from "./api";
import AssetDetail from "./components/AssetDetail";
import Overview from "./components/Overview";
import Performance from "./components/Performance";
import Portfolio from "./components/Portfolio";
import ResearchQueue from "./components/ResearchQueue";
import Screener from "./components/Screener";
import MeridianDemo from "./legacy/MeridianDemo";
import "./styles.css";

const TABS = [
  { id: "overview", label: "Overview" },
  { id: "screener", label: "Screener" },
  { id: "portfolio", label: "Portfolio" },
  { id: "performance", label: "Model performance" },
  { id: "queue", label: "Research queue" },
  { id: "demo", label: "UI demo (simulated)" },
];

export default function App() {
  const [tab, setTab] = useState("overview");
  const [symbol, setSymbol] = useState(null);
  const [health, setHealth] = useState({ status: "loading" });
  const [search, setSearch] = useState("");

  useEffect(() => {
    api
      .health()
      .then((data) => setHealth({ status: "ready", data }))
      .catch((error) => setHealth({ status: "error", error }));
  }, []);

  const selectAsset = useCallback((next) => {
    setSymbol(next);
    setTab("asset");
  }, []);

  const submitSearch = (event) => {
    event.preventDefault();
    if (search.trim()) selectAsset(search.trim().toUpperCase());
  };

  return (
    <div className="app">
      <header className="masthead">
        <div className="brand">
          <h1>Investment Research Engine</h1>
          <p>
            Decision support only — not investment advice. Every figure is a model
            estimate that can be wrong.
          </p>
        </div>
        <form className="search" onSubmit={submitSearch}>
          <input
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Analyse a symbol…"
            aria-label="Symbol"
          />
          <button type="submit">Open</button>
        </form>
      </header>

      {health.status === "error" && (
        <div className="callout callout-error">
          <strong>The research API is not reachable.</strong> Start it with{" "}
          <code>research-engine serve</code>. Until then no live data can be
          shown — this dashboard never substitutes placeholder numbers.
          <span className="muted"> ({health.error.message})</span>
        </div>
      )}

      {health.status === "ready" && (
        <div className="status-bar">
          <span>{health.data.assets} assets</span>
          <span>{health.data.prices?.toLocaleString()} price rows</span>
          <span>{health.data.recommendations} recommendations</span>
          <span>
            latest analysis:{" "}
            {health.data.latest_analysis || "never — run `research-engine daily`"}
          </span>
        </div>
      )}

      <nav className="tabs">
        {TABS.map((entry) => (
          <button
            key={entry.id}
            type="button"
            className={tab === entry.id ? "active" : ""}
            onClick={() => setTab(entry.id)}
          >
            {entry.label}
          </button>
        ))}
        {symbol && (
          <button
            type="button"
            className={tab === "asset" ? "active" : ""}
            onClick={() => setTab("asset")}
          >
            {symbol}
          </button>
        )}
      </nav>

      <main className="content">
        {tab === "overview" && <Overview onSelectAsset={selectAsset} />}
        {tab === "screener" && <Screener onSelectAsset={selectAsset} />}
        {tab === "portfolio" && <Portfolio onSelectAsset={selectAsset} />}
        {tab === "performance" && <Performance />}
        {tab === "queue" && <ResearchQueue onSelectAsset={selectAsset} />}
        {tab === "asset" && symbol && (
          <AssetDetail symbol={symbol} onBack={() => setTab("overview")} />
        )}
        {tab === "demo" && (
          <div className="demo-wrapper">
            <div className="callout callout-warning demo-banner">
              <strong>Simulated data.</strong> This tab is the original Meridian
              terminal mock-up. Every number in it is generated by a seeded
              random walk and describes nothing real. It is kept as a UI
              reference only.
            </div>
            <MeridianDemo />
          </div>
        )}
      </main>

      <footer className="footer">
        Research and decision-support software. Predictions are uncertain,
        backtests are simulations, and past performance does not guarantee future
        results. This system never places trades.
      </footer>
    </div>
  );
}
